=== sarnold/seedit/seedit-policy/src/base_policy/spdl_spec.dtd
<!ELEMENT spdl (unsupported, integrate+, group+)>
<!ELEMENT unsupported (description, section+)>
<!ELEMENT section  (description, moredescription?, rules)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT moredescription (#PCDATA)>
<!ELEMENT rules (rule*)>
<!ELEMENT rule (domain+,type+, secclass+,permission+)>
<!ATTLIST rule value CDATA #REQUIRED
           disabled (yes|no) "no"
>
<!ELEMENT domain EMPTY>
<!ATTLIST domain value CDATA #REQUIRED>
<!ELEMENT type EMPTY>
<!ATTLIST type value CDATA #REQUIRED>
<!ELEMENT secclass EMPTY>
<!ATTLIST secclass value CDATA #REQUIRED>

<!ELEMENT permission EMPTY>
<!ATTLIST permission value CDATA #REQUIRED
          nomatch (yes|no) "no"
>


<!ELEMENT integrate (description, moredescription?,option+)>
<!ATTLIST integrate value CDATA #REQUIRED>

<!ELEMENT option (comment?,macro,rules)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT macro (#PCDATA)>
<!ATTLIST macro value CDATA #REQUIRED>
<!ATTLIST option value CDATA #REQUIRED
          suboption CDATA #IMPLIED
          internal (yes|no) "no"
          category CDATA #IMPLIED
>

<!ELEMENT group (element+)>
<!ATTLIST group value CDATA #REQUIRED>
<!ELEMENT element EMPTY>
<!ATTLIST element value CDATA #REQUIRED>

=== sarnold/seedit/core/config/base_policy/spdl_spec.xml
<?xml version="1.0" ?>
<!DOCTYPE spdl
  SYSTEM 'spdl_spec.dtd'>
<spdl>
  <unsupported>
    <description>Unsupported permission</description>
    <section>
      <description>Dead Permission</description>
      <rules>
	<rule disabled="yes" value="allow">
	  <domain value="global"/>
	  <type value="file_type"/>
	  <secclass value="dir"/><secclass value="file"/><secclass value="lnk_file"/><secclass value="sock_file"/><secclass value="fifo_file"/><secclass value="chr_file"/><secclass value="blk_file"/>
	  <permission value="swapon"/>
	</rule>
	<rule disabled="yes" value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="all_socket_class"/>
	  <permission value="relabelfrom"/>
	  <permission value="relabelto"/>
	</rule>
	<rule disabled="yes" value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="unix_stream_socket"/>
	  <permission value="newconn"/>
	  <permission value="acceptfrom"/>
	</rule>
	<rule disabled="yes" value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="netlink_firewall_socket"/>
	  <permission value="nlmsg_read"/>
	</rule>
	<rule disabled="yes" value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="netlink_ip6fw_socket"/>
	  <permission value="ioctl"/><permission value="read"/><permission value="write"/><permission value="create"/><permission value="getattr"/><permission value="setattr"/><permission value="lock"/><permission value="relabelfrom"/><permission value="relabelto"/><permission value="append"/><permission value="bind"/><permission value="connect"/><permission value="listen"/><permission value="accept"/><permission value="getopt"/><permission value="setopt"/><permission value="shutdown"/><permission value="recvfrom"/><permission value="sendto"/><permission value="recv_msg"/><permission value="send_msg"/><permission value="name_bind"/>
	  <permission value="nlmsg_read"/>
	  <permission value="nlmsg_write"/>
	</rule>
	<rule disabled="yes" value="allow">
	  <domain value="global"/>
	  <type value="self"/>
	  <secclass value="netlink_tcpdiag_socket"/>
	  <permission value="nlmsg_write"/>
	</rule>
	<rule disabled="yes" value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="ipc"/>
	  <permission value="create"/>
	  <permission value="destroy"/>
	  <permission value="getattr"/>
	  <permission value="setattr"/>
	  <permission value="read"/>
	  <permission value="write"/>
	  <permission value="associate"/>
	  <permission value="unix_read"/>
	  <permission value="unix_write"/>
	</rule>
      </rules>
    </section>
    <section>
      <description>Unsupported features in SPDL</description>
      <rules>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="security_t"/>
	  <secclass value="security"/>
	  <permission value="compute_member"/>
	  <permission value="setcheckreqprot"/>
	</rule>
      </rules>
    </section>
    <section>
      <description>Unsupported because related to DAC and POSIX capabilities  </description>
      <rules>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="process"/>
	  <permission value="getcap"/>
	  <permission value="setcap"/>
	</rule>
      </rules>
    </section>
    <section>
      <description>Unsupported because low effect to security</description>
      <rules>	
      <rule value="allow">
	  <domain value="global"/>
	  <type value="file_type"/>
	  <type value="global"/>
	  <secclass value="dir"/><secclass value="file"/><secclass value="lnk_file"/><secclass value="sock_file"/><secclass value="fifo_file"/><secclass value="chr_file"/><secclass value="blk_file"/>
	  <permission value="getattr"/>
	</rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="process"/>
	  <permission value="getsched"/>
	  <permission value="getsession"/>
	  <permission value="getpgid"/>
	  <permission value="setpgid"/>
	  <permission value="noatsecure"/>
	  <permission value="siginh"/>
	  <permission value="rlimitinh"/>
	  <permission value="fork"/>
	  <permission value="share"/>
	</rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="system"/>
	  <permission value="ipc_info"/>
	</rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="self"/>
	  <secclass value="capability"/>
	  <permission value="lease"/>
	</rule>
	<rule value="allow">
	  <domain value="file_type"/>
	  <type value="fs_type"/>
	  <secclass value="filesystem"/>
	  <permission value="associate"/>
	</rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="fs_type"/>
	  <secclass value="filesystem"/>
	  <permission value="getattr"/>
	  <permission value="quotaget"/>
	</rule>
      </rules>
    </section>
    <section>
      <description> Unsupported because of complete overlap </description>
      <rules>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="self"/>
	  <secclass value="capability"/>
	  <permission value="kill"/>
	  <permission value="ipc_owner"/>
	  <permission value="net_bind_service"/>
	  <permission value="sys_ptrace"/>
	  <permission value="audit_write"/>
	</rule>

	<rule value="allow">
	  <domain value="global"/>
	  <type value="file_type"/>
	  <type value="global"/>
	  <secclass value="dir"/>
	  <permission value="add_name"/>
	  <permission value="remove_name"/>
	</rule>

      </rules>
    </section>
    <section>
      <description> Unsupported because of Partly overlap</description>
      <rules>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="process"/>
	  <permission value="setsched"/>
	  <permission value="setrlimit"/>
	</rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="self"/>
	  <secclass value="capability"/>
	  <permission value="audit_control"/>
	</rule>
      </rules>
    </section>
    <section>
      <description>Implicit overlap</description>
      <rules>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="fd"/>
	  <permission value="use"/>
	</rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="process"/>
	  <permission value="setexec"/>
	</rule>
  	<rule value="allow">
	  <domain value="global"/>
	  <type value="self"/>
	  <secclass value="tcp_socket"/>
	  <permission value="bind"/><permission value="listen"/><permission value="accept"/><permission value="connect"/><permission value="create"/><permission value="shutdown"/><permission value="getattr"/><permission value="getopt"/><permission value="setopt"/><permission value="ioctl"/><permission value="lock"/><permission value="setattr"/>
	  <permission value="read"/>
	  <permission value="write"/>
	  <permission value="append"/>
	  </rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="self"/>
	  <secclass value="udp_socket"/>
	  <permission value="bind"/><permission value="listen"/><permission value="accept"/><permission value="connect"/><permission value="create"/><permission value="shutdown"/><permission value="getattr"/><permission value="getopt"/><permission value="setopt"/><permission value="ioctl"/><permission value="lock"/><permission value="setattr"/>
	  <permission value="read"/>
	  <permission value="write"/>
	  <permission value="append"/>
	  </rule>

 
	<rule value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="unix_dgram_socket"/>
    <permission value="ioctl"/>
    <permission value="getattr"/>
    <permission value="setattr"/>
    <permission value="lock"/>
    <permission value="relabelfrom"/>
    <permission value="relabelto"/>
    <permission value="create"/>
    <permission value="shutdown"/>
    <permission value="getopt"/>
    <permission value="setopt"/>
	</rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="global"/>
	  <secclass value="unix_stream_socket"/>
    <permission value="ioctl"/>
    <permission value="getattr"/>
    <permission value="setattr"/>
    <permission value="lock"/>
    <permission value="relabelfrom"/>
    <permission value="relabelto"/>
    <permission value="create"/>
    <permission value="shutdown"/>
    <permission value="getopt"/>
    <permission value="setopt"/>
	</rule>


      </rules>
    </section>
    <section>
      <description>Pending.. May be changed</description>
      <rules>
        <rule value="allow">
	  <domain value="global"/>
	  <type value="unlabeled_t"/>
	  <secclass value="packet"/>
	  <permission value="send"/>
	  <permission value="recv"/>
        </rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="self"/>
	  <secclass value="packet_socket"/>
	  <permission value="ioctl"/><permission value="read"/><permission value="write"/><permission value="create"/><permission value="getattr"/><permission value="setattr"/><permission value="lock"/><permission value="relabelfrom"/><permission value="relabelto"/><permission value="append"/><permission value="bind"/><permission value="connect"/><permission value="listen"/><permission value="accept"/><permission value="getopt"/><permission value="setopt"/><permission value="shutdown"/><permission value="recvfrom"/><permission value="sendto"/><permission value="recv_msg"/><permission value="send_msg"/><permission value="name_bind"/>
	</rule>
	<rule value="allow">
	  <domain value="global"/>
	  <type value="self"/>
	  <secclass value="key_socket"/>
