=== sarnold/seedit/seedit-converter/xml/simplified_policy.dtd
<!ELEMENT policy ( section+ )>
<!ELEMENT section (comment?,program* user*, domaintrans*,(include|allowfile|allowdev|allowtmp|allownet|allowcom|allowproc|allowfs|allowpriv|allowseop|allowkernel)+)>

<!ATTLIST section id  ID #REQUIRED
                  type (role|domain) #REQUIRED            
>
<!ELEMENT comment (#PCDATA)>

<!ELEMENT domaintrans (comment?, parentdomain+, entrypoint*)>
<!ELEMENT parentdomain (#PCDATA)>
<!ELEMENT entrypoint (#PCDATA)>

<!ELEMENT program (comment?, path+)>

<!ELEMENT user (comment?,uname)>
<!ELEMENT uname (#PCDATA)>

<!ELEMENT allowfile (comment?, path, (permission | label)* ) >
<!ATTLIST allowfile type (allow|deny)  #REQUIRED>

<!ELEMENT include (comment?, path)>

<!ELEMENT path (#PCDATA)>
<!ELEMENT permission (#PCDATA)>
<!ELEMENT label (#PCDATA)>


<!ELEMENT allownet (comment?, protocol, port*, node?, netif?, domain*, permission+) >
<!ATTLIST allownet type (allow)  #REQUIRED>
<!ELEMENT protocol (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT node (#PCDATA)>
<!ELEMENT netif (#PCDATA)>
<!ELEMENT domain (#PCDATA)>


<!ELEMENT allowcom (comment?, option, domain, permission*)>
<!ELEMENT option (#PCDATA)>
<!ATTLIST allowcom type (allow)  #REQUIRED>


<!ELEMENT allowproc (comment?, option, permission+)>
<!ATTLIST allowproc type (allow)  #REQUIRED>

<!ELEMENT allowfs (comment?, fs, (label|permission)+)>
<!ATTLIST allowfs type (allow|exclusive)  #REQUIRED>
<!ELEMENT fs (#PCDATA)>

<!ELEMENT allowdev (comment?, option, path*, role?, permission*)>
<!ATTLIST allowdev type (allow)  #REQUIRED>
<!ELEMENT role (#PCDATA)>

<!ELEMENT allowtmp (comment?, (dir|fs), name  , permission?>
<!ATTLIST allowtmp type (allow)  #REQUIRED>
<!ELEMENT dir (#PCDATA)>
<!ELEMENT name (#PCDATA)>


<!ELEMENT allowpriv (comment?, option)>
<!ATTLIST allowpriv type (allow)  #REQUIRED>
<!ELEMENT allowkernel (comment?, option)>
<!ATTLIST allowkernel type (allow)  #REQUIRED>
<!ELEMENT allowseop (comment?, option)>
<!ATTLIST allowseop type (allow)  #REQUIRED>

=== sarnold/seedit/seedit-gui/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policy SYSTEM "simplified_policy.dtd">
<policy>
  <section id="global" type="domain">
    <comment>#Author: Yuichi Nakamura &lt;ynakam@gwu.edu&gt;
#Defines default protection
</comment>
    <allowdev type="allow">
      <comment>#root to device dir
</comment>
      <option>root</option>
      <path>/dev</path>
    </allowdev>
    <allowfile type="allow" only="yes">
      <comment>#read-only to system files
</comment>
      <path>/</path>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/var</path>
      <permission>r</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/mnt</path>
      <permission>r</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment>#can use commands and libs
</comment>
      <path>/lib</path>
      <permission>r</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/usr</path>
      <permission>r</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/bin</path>
      <permission>r</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/sbin</path>
      <permission>r</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/etc</path>
      <permission>r</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment>##can read tmp
</comment>
      <path>/tmp</path>
      <permission>r</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment>#device protected
</comment>
      <path>/dev</path>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment>#can use some devices 
</comment>
      <path>/dev/console</path>
      <permission>r</permission>
      <permission>w</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/dev/null</path>
      <permission>r</permission>
      <permission>w</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/dev/zero</path>
      <permission>r</permission>
      <permission>w</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/dev/random</path>
      <permission>r</permission>
      <permission>w</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/dev/urandom</path>
      <permission>r</permission>
      <permission>x</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="deny">
      <comment>###Default deny  files
#some critical device
</comment>
      <path>/dev/kmem</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/dev/mem</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/dev/port</path>
    </allowfile>
    <allowfile type="deny">
      <comment>#protect SELinux config
</comment>
      <path>/etc/selinux/seedit</path>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/etc/selinux/seedit-devel</path>
      <permission>r</permission>
      <permission>s</permission>
    </allowfile>
    <allowfile type="deny">
      <comment>#password files
</comment>
      <path>/etc/shadow-</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/etc/shadow</path>
    </allowfile>
    <allowfile type="deny">
      <comment>#admin's root dir
</comment>
      <path>/root</path>
    </allowfile>
    <allowfile type="deny">
      <comment>#Cannot access to shell
</comment>
      <path>/bin/sh</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/bin/bash</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/bin/tcsh</path>
    </allowfile>
    <allowfile type="allow">
      <comment>## logs
</comment>
      <path>/var/log</path>
      <permission>s</permission>
    </allowfile>
    <allowfile type="deny">
      <comment>#SELinux logs
</comment>
      <path>/var/log/audit</path>
    </allowfile>
    <allowfile type="deny">
      <comment>#Apache lgos
</comment>
      <path>/var/log/httpd</path>
    </allowfile>
    <allowfile type="deny">
      <comment># protect homepages
</comment>
      <path>/var/www</path>
    </allowfile>
    <allowfile type="deny">
      <comment>##protect cron related files
</comment>
      <path>/etc/crontab</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/etc/cron.d</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/etc/cron.weekly</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/var/spool/cron</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/var/spool/anacron</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/etc/cron.hourly</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/etc/cron.daily</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/etc/cron.monthly</path>
    </allowfile>
    <allowcom type="allow">
      <comment>###
# allow communication within domain
</comment>
      <option>msg</option>
      <domain>self</domain>
      <permission>r</permission>
      <permission>w</permission>
    </allowcom>
    <allowcom type="allow">
      <comment/>
      <option>msgq</option>
      <domain>self</domain>
      <permission>r</permission>
      <permission>w</permission>
    </allowcom>
    <allowcom type="allow">
      <comment/>
      <option>pipe</option>
      <domain>self</domain>
      <permission>r</permission>
      <permission>w</permission>
    </allowcom>
    <allowcom type="allow">
      <comment/>
      <option>sem</option>
      <domain>self</domain>
      <permission>r</permission>
      <permission>w</permission>
    </allowcom>
    <allowcom type="allow">
      <comment/>
      <option>shm</option>
      <domain>self</domain>
      <permission>r</permission>
      <permission>w</permission>
    </allowcom>
    <allowcom type="allow">
      <comment/>
      <option>sig</option>
      <domain>init_t</domain>
      <permission>c</permission>
    </allowcom>
    <allowcom type="allow">
      <comment/>
      <option>sig</option>
      <domain>self</domain>
      <permission>c</permission>
      <permission>k</permission>
      <permission>s</permission>
      <permission>n</permission>
      <permission>o</permission>
    </allowcom>
    <allowcom type="allow">
      <comment/>
      <option>tcp</option>
      <domain>self</domain>
    </allowcom>
    <allowcom type="allow">
      <comment/>
      <option>udp</option>
      <domain>self</domain>
    </allowcom>
    <allowcom type="allow">
      <comment/>
      <option>unix</option>
      <domain>self</domain>
    </allowcom>
    <allowproc type="allow">
      <comment>#/proc/&lt;self pid&gt;
</comment>
      <option>self</option>
      <permission>r</permission>
    </allowproc>
    <allowfs type="allow">
      <comment># read only access to some misc file systems
</comment>
      <fs>proc</fs>
      <permission>r</permission>
      <permission>s</permission>
    </allowfs>
    <allowfs type="allow">
      <comment/>
      <fs>usbfs</fs>
      <permission>r</permission>
      <permission>s</permission>
    </allowfs>
    <allowfs type="allow">
      <comment/>
      <fs>sysfs</fs>
      <permission>r</permission>
      <permission>s</permission>
    </allowfs>
    <allowfs type="allow">
      <comment/>
      <fs>tmpfs</fs>
      <permission>s</permission>
    </allowfs>
    <allowfs type="allow">
      <comment/>
      <fs>xattrfs</fs>
      <permission>s</permission>
    </allowfs>
    <allowfs type="allow">
      <comment>#Everyone can use tmpfs
</comment>
      <fs>tmpfs</fs>
      <permission>r</permission>
      <permission>w</permission>
      <permission>s</permission>
    </allowfs>
    <allowfile type="deny">
      <comment>#about samba
</comment>
      <path>/etc/samba</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/var/log/samba</path>
    </allowfile>
    <allowfile type="deny">
      <comment>#for named
</comment>
      <path>/var/named</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/etc/named.conf</path>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/etc/named.boot</path>
    </allowfile>
    <allowfile type="deny">
      <comment>#for mysqld
</comment>
      <path>/var/lib/mysql</path>
    </allowfile>
    <allowfile type="deny">
      <comment>#for postfix and sendmail
</comment>
      <path>/var/spool/postfix</path>
    </allowfile>
    <allowfile type="allow">
      <comment/>
      <path>/var/spool/mail</path>
      <permission>s</permission>
    </allowfile>
    <allowfile type="deny">
      <comment/>
      <path>/etc/postfix</path>
    </allowfile>
    <allowdev type="allow">
      <comment>###
# everyone can read/write tty/pts, but can not create
</comment>
      <option>allterm</option>
      <role>general</role>
      <permission>r</permission>
      <permission>w</permission>
    </allowdev>
    <allowdev type="allow">
      <comment/>
      <option>allterm</option>
